### ISSUE TITLE
Any plans for compatibility with version 8

### ISSUE THREAD

**Issue by katalysis** [c5labs/google-analytics#1]
Just tried installing on 8.2.1 and there's an error in the installation process.  Are there any plans to make the package compatible withversion 8?

**Comment by olsgreen** [comment]
There were a few issues with 8.x caching which I've just fixed.

Although, these wouldn't have caused any errors installing. Did you install straight from the repository or download a release zip? The code in the repository does not include the composer assets, so wouldn't work straight out of the box. I release the addons on the website and via the repos release page which include a zip with all of the composer assets.

You can download 0.9.4 here: 
https://github.com/c5labs/google-analytics/releases/download/0.9.4/google-analytics.zip

Try this and let me know how you get on.

**Comment by katalysis** [comment]
Working now - many thanks.
