### ISSUE TITLE
Invalid_grant

### ISSUE THREAD

**Issue by hemiipatu** [c5labs/google-analytics#2]
There seems to be an issue when trying to generate an Access Token. I've tried a few times now and I am being greeted by a message:

> An unexpected error occurred.

> invalid_grant

Do you know what might be the cause of this or how I might fix it? I am using Concrete5 v8.

**Comment by olsgreen** [comment]
Whats the exact version of concrete5 you're using? 8.x.x...

Also, where are you getting this message? When trying to save the token from Google?

**Comment by hemiipatu** [comment]
Hi there, sorry about the late reply: From "Environment Information" on concrete5's dashboard, I am running the below:

Core Version - 8.3.2
Version Installed - 8.3.2
Database Version - 20180122213656

I am getting the message when trying to save the Token using the UI that is provided by the plugin.

**Comment by hemiipatu** [comment]
Hmm this is interesting, I tried it again today and I am now being presented with:

> This account has no Google Analytics Profiles

I'm not sure what this means to be honest... I have an account setup and working already.

**Comment by olsgreen** [comment]
That usually means that the account you authenticated with to obtain the token doesn't have Google Analytics setup or if it does it has no sites registered against it. Is the Google account your using new? Did you recently add the sites to analytics?

**Comment by hemiipatu** [comment]
Hi there, the analytics account I'm using is about a month old now. I'd used (originally) the embed that they provide on an old site, however the domain is the same as I've recently setup a new site using concrete.

**Comment by olsgreen** [comment]
Can you try clearing the sites cache and then trying again? Dashboard > System Settings > Optimisation > Clear Cache

I'm going to try and reproduce the issue, let me know whether the above works.

**Comment by hemiipatu** [comment]
So I've cleared the cache and re-done the steps I had done before. Unfortunately they yielded no results.

**Comment by olsgreen** [comment]
Can you send me a support request via https://c5labs.com/support so I can get your e-mail address, this seems as if it's a problem with your analytics account, I'd like to give you some test credentials to see whether you can successfully add the account using them.

**Comment by hemiipatu** [comment]
Apologies for the late reply! I tried going to your site but I am met with an error.
![capture](https://user-images.githubusercontent.com/16671116/36067013-d4f819ec-0eac-11e8-9854-c3254ea4c06e.PNG)

**Comment by olsgreen** [comment]
Ooops! Try again please 👍

**Comment by olsgreen** [comment]
Closed as this is no longer the issue.
