### ISSUE TITLE
The add-on causes viewing issues.

### ISSUE THREAD

**Issue by hemiipatu** [c5labs/google-analytics#4]
I posted an issue on the concrete5 forums of an issue where users _(sometimes admin)_ of a site would be presented with an error which we concluded is because of this line of code;

> https://github.com/c5labs/google-analytics/blob/master/src/GoogleAna...

Changing it to `$permissions->canViewPage();` seems to resolve the issue.

**Comment by olsgreen** [comment]
Thanks for reporting, I'll get it fixed in the next release.

**Comment by hemiipatu** [comment]
No worries at all, it's a seriously helpful add-on so will do what I can to help. I've found another issue too which I will report in a moment.
