### ISSUE TITLE
Error being thrown which causes entire site to be inaccessible at random.

### ISSUE THREAD

**Issue by hemiipatu** [c5labs/google-analytics#5]
I'm unsure of what's causing this error, but it is extremely random and generally presents itself when visiting the site. This issue can be reproduced regardless of whether a user is logged in or not.

I've provided a screenshot of the error logs below but it is the line; `throw new IdentityProviderException($error, $code, $data);` 

![capture](https://user-images.githubusercontent.com/16671116/37487183-b1bd244a-2888-11e8-9ff2-95854364398e.PNG)

**Comment by olsgreen** [comment]
Again, thanks! I'll get these issues resolved and a new version out this weekend.

**Comment by hemiipatu** [comment]
No worries at all, it's a pleasure to help where I can! 👍

**Comment by cotonbranding** [comment]
Has this been resolved as I am having problems in edit mode...

**Comment by cotonbranding** [comment]
And I can't remove this add-on without it causing further problems

**Comment by olsgreen** [comment]
@cotonbranding Nope, but i'll be releasing an update within the next hour if you can hold on!

**Comment by olsgreen** [comment]
@cotonbranding I've just released 0.9.5 which you can download from [here](https://github.com/c5labs/google-analytics/releases/download/0.9.5/google-analytics.zip), replace the files it should stop the errors and fix the issues. If you could report back that would be great. 👍

**Comment by cotonbranding** [comment]
Seems to be working better - thanks
